apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zkui
  labels:
    app: zkui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zkui
    spec:
      containers:
        - name: zkui
          image: gary0416/zkui:2.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 9090
              name: zkui
          env:
            - name: ZKLIST
              value: "zk-0.zk:2181,zk-1.zk:2181,zk-2.zk:2181"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zkui
  name: zkui
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: zkui
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zkui
spec:
  rules:
    - host: zkui.gary.your-domain.com
      http:
        paths:
          - backend:
              serviceName: zkui
              servicePort: 9090
